# Generated by Django 2.2 on 2022-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingapp', '0002_auto_20220320_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
